// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjt4C-oPz-rjLvtkL5T5spT5bdrD03fXc',
    appId: '1:934505990792:web:135d2a691df911f75e6d3d',
    messagingSenderId: '934505990792',
    projectId: 'takecare-idealab',
    authDomain: 'takecare-idealab.firebaseapp.com',
    storageBucket: 'takecare-idealab.firebasestorage.app',
    measurementId: 'G-QTX6N56VXX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnrna5AkSBSn5n-3P0bSP97COVoZXRqpw',
    appId: '1:934505990792:android:88d9905ed3d945145e6d3d',
    messagingSenderId: '934505990792',
    projectId: 'takecare-idealab',
    storageBucket: 'takecare-idealab.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC--J00Zh1e_ekCpxw1VflIA0uKHkXvjWA',
    appId: '1:934505990792:ios:7784e256fb283da25e6d3d',
    messagingSenderId: '934505990792',
    projectId: 'takecare-idealab',
    storageBucket: 'takecare-idealab.firebasestorage.app',
    iosBundleId: 'com.example.takecare',
  );
}
